[build]
  publish = "_site"
  command = "npm run build"
  functions = "functions" # https://damato.design/searchIndex.json

[[redirects]]
  from = "/"
  to = "/introduction"
  status = 200 # Hide the url as index

[[plugins]]
  package = "netlify-plugin-a11y"
  [plugins.inputs]
    resultMode = "warn"
